# Generated by Django 2.2.6 on 2019-10-11 17:46

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('alt_phone', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('Realtor', 'Realtor'), ('FA', 'FA'), ('Builder', 'Builder'), ('Other', 'Other')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
