# Generated by Django 2.2.6 on 2019-10-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('loan_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Refi', 'Refi'), ('HEL', 'HEL'), ('HELOC', 'HELOC')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
