# Generated by Django 2.2.6 on 2019-10-11 17:32

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alt_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
    ]
