# Generated by Django 2.2.6 on 2019-10-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191013_0311'),
        ('leads', '0002_auto_20191011_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Contact'),
        ),
    ]
